### ISSUE TITLE
Already admin on Guest account

### ISSUE THREAD

**Issue by SEAPUNK** [Vozzie/uacscript#1]
I ran your script, but it keeps saying I already have admin, even though UAC is enabled.

It does the same for the Guest account, which is supposed to have the least privilege.

Am I missing something here?

**Comment by Vozzie** [comment]
Did you run it on Windows 7 with UAC settings to default? The machine i tested only had one admin account and the UAC settings to default.

**Comment by SEAPUNK** [comment]
UAC settings were default, yes. I even upped the UAC settings, but it gave me the same result.

One admin account, one guest account. Script run from both admin or guest on default UAC settings says that it already has admin.

**Comment by Vozzie** [comment]
Can you give more details on how you've started the script. I think it works on other machines. It's been tested on mine, (quite a fresh re-install) and on a machine of somebody i know. And somebody translated the script into powershell. 

Normally a script can't write to certain sections in the registry. You get the message because the first time you run the script it can write to the registry. (If the key is still there, remove it before each test.)

You might have local "issues" on your machine. Do you have a VM to test the script?

**Comment by SEAPUNK** [comment]
I started the script by double-clicking on it.

**Comment by SEAPUNK** [comment]
I don't have a VM to test it, at least not yet.

**Comment by john-audi** [comment]
Hi , I'm suffering from the same problem, can you please specify the reason ?

**Comment by Vozzie** [comment]
I did specify the reason why the script gives this message, as it is straightforward. Normally an administrative user with UAC settings at default has no right to write to certain parts of the registry. (The function HasAdmin tries to write and returns True if no error occurred.)

I suspect your UAC settings are not default or your user settings are changed.

**Comment by dulsao** [comment]
Hi.
I’m having the exact same output as reported above.
My setup :
Win7 machine patched to 10/2015
UAC default settings
When I run the script, I get the same error as repoted, and no registry key exists with the name “HKLM\SOFTWARE\Microsoft\RandomKey”. attached screenshot after the run, showing no reg key added. http://postimg.org/image/3l8hu5kar/

Has consistent results with testing these environments :
1.  Machine patched to 3/2015
2.  Admin account (default UAC)
3.  User account (default UAC)

I would gladly share any additional details you might need
Thank you,

Dulsao
